// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgujxsipafjjailnzufv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNndWp4c2lwYWZqamFpbG56dWZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNTA3ODUsImV4cCI6MjA2NDYyNjc4NX0.P-m4_T-SmHvKcrxye-bQYE387AaRF-8zdJoGK8viG7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);